var vitamins = [
  "Vitamin B1 (Thiamine)",
  "Vitamin B2 (Riboflavin)",
  "Vitamin B3 (Niacin)",
  "Vitamin B5 (Pantothenic acid)",
  "Vitamin B6",
  "Vitamin B7 (Biotin)",
  "Vitamin B9 (Folic acid)",
  "Vitamin B12",
  "Vitamin C",
  "Vitamin D",
  "Vitamin E",
  "Vitamin K",
  "Calcium",
  "Iron",
  "Magnesium",
  "Zinc",
  "Selenium",
  "Copper",
  "Manganese",
  "Chromium",
  "Molybdenum",
  "Potassium",
  "Iodine",
  "Chloride",
  "Phosphorus",
  "Biotin",
  "Choline",
  "Inositol",
  "PABA (para-aminobenzoic acid)",
  "Lycopene",
  "Lutein",
  "zeaxanthin",
  "Beta-carotene",
  "Astaxanthin",
  "Coenzyme Q10",
  "Glutathione",
  "Alpha-lipoic acid",
  "Omega-3 fatty acids (EPA and DHA)",
  "Vitamin A",
];
var perfumes = [
  "Chanel No. 5",
  "Joy by Jean Patou",
  "Shalimar by Guerlain",
  "Arpege by Lanvin",
  "L'Air du Temps by Nina Ricci",
  "Youth Dew by Estée Lauder",
  "First by Van Cleef & Arpels",
  "Opium by Yves Saint Laurent",
  "Aromatics Elixir by Clinique",
  "Charlie by Revlon",
  "Anais Anais by Cacharel",
  "Obsession by Calvin Klein",
  "Giorgio by Giorgio Beverly Hills",
  "Paloma Picasso by Paloma Picasso",
  "Lou Lou by Cacharel",
  "Drakkar Noir by Guy Laroche",
  "Fahrenheit by Christian Dior",
  "Eternity by Calvin Klein",
  "White Diamonds by Elizabeth Taylor",
  "Issey Miyake by Issey Miyake",
];
var shoeTypes = [
  "Sneakers",
  "Running shoes",
  "Basketball shoes",
  "Football shoes",
  "Tennis shoes",
  "Hiking boots",
  "Dress shoes",
  "Loafers",
  "Sandals",
  "Flip flops",
  "Slippers",
  "Clogs",
  "Boat shoes",
  "Oxford shoes",
  "Wingtip shoes",
  "Chelsea boots",
  "Chukka boots",
  "Cowboy boots",
  "Rain boots",
  "Snow boots",
  "Work boots",
  "Combat boots",
  "Dance shoes",
  "Ballet flats",
  "High heels",
  "Stilettos",
  "Platform shoes",
  "Mary Janes",
  "Knee-high boots",
];
